name: Go

on:
  push:
    branches: [development, staging, main]
    paths:
      - 'src/host/**'
      - 'go.mod'
      - 'main.go'
  pull_request:
    branches: [development, staging, main]
    paths:
      - 'src/host/**'
      - 'go.mod'
      - 'main.go'

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: make build

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run tests
      run: go test -race -vet=off -ldflags="-r $GITHUB_WORKSPACE/lib" ./...
